name: Deploy na Produção

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Instalar chave SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: "SHA256:c6/a040J2J3TuUt7dkWsJ96va8Wisol1kunjNKEd9lQ"

      - name: Adicionar host do servidor aos conhecidos
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H  >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      - name: Fazer o deploy
        run: |
          ssh "SHA256:c6/a040J2J3TuUt7dkWsJ96va8Wisol1kunjNKEd9lQ@147.93.70.17" "cd /var/www/html && git pull origin main"